### ISSUE TITLE
OOM Issue

### ISSUE THREAD

**Issue by GSK666** [jy0205/Pyramid-Flow#31]
What a great job. When i use A800 80G with default parameters to infer the 768P video, I find that the GPU memory increases first and then decreases. The step inference is fine, but an OOM error is reported during the final VAE decode, even if I reduce the temp parameter and set save_memory parameter is True.
![0zm6n12000g3a47sl9139](https://github.com/user-attachments/assets/a126be13-97e0-44d8-b42c-dcd5193f5108)
![0zm0512000g39w4430EBC](https://github.com/user-attachments/assets/24e60dd2-ac8f-4b60-b00a-fcd0e8ff2a8a)
Looking forward to your reply, Thank you.

**Comment by jy0205** [comment]
Thanks for your interests. Have you added the `model.vae.enable_tiling()`? If not, the `save_memory=True` does not work.

**Comment by GSK666** [comment]
Thank you so much.
model.vae.enable_tiling()
This configuration solved my problem.

**Comment by feifeiobama** [comment]
Glad to hear you have resolved this issue. The 768p model does not support dynamic resolution because we did not use a variable-resolution training strategy. We trained the model first on 384p video and then on 768p video.

**Comment by harryaskham** [comment]
I'm also finding OOM on a 24gb 7900XTX (torch rocm 6.1 python 3.9 - I realise unsupported, was the only config available to me on NixOS easily) at 384p in the final VAE decode - memory usage is about 18gb throughout generation then tries to allocate ~6gb at the end and fails.

**Comment by feifeiobama** [comment]
If the OOM is caused by VAE and you have already enabled the `model.vae.enable_tiling()` and `save_memory=True` options, then perhaps the solution is to modify the following code and set the `tile_sample_min_size` parameter to 128:
https://github.com/jy0205/Pyramid-Flow/blob/6eca678a40acac4c37e777ef9fd13a703850116a/pyramid_dit/pyramid_dit_for_video_gen_pipeline.py#L680-L682

**Comment by FurkanGozukara** [comment]
hi @feifeiobama  could you make it parameter passable rather than manual correction?

I plan to improve gradio app and let user change those crucial parameters but i dont want to modify your pipeline

**Comment by feifeiobama** [comment]
We haven't fully tested our VAE decoder and are unsure if it will work with a smaller `tile_sample_min_size`, so we'd rather stick with a larger and safer default `tile_sample_min_size`. Of course, you can change the inference pipeline and make the parameter passable, perhaps in a separate pull request.

> hi @feifeiobama could you make it parameter passable rather than manual correction?
> 
> I plan to improve gradio app and let user change those crucial parameters but i dont want to modify your pipeline

**Comment by harryaskham** [comment]
I can confirm that dropping `tile_sample_min_size` to 128 worked for me with `save_memory=True` and `model.vae.enable_tiling()`; peak VRAM was around 22gb @ 384p with a 5s clip taking around 3 mins to generate on a 7900XTX.

I tried dropping 128->64->32->16->8 to see if 768p would fit, but it OOMs even at `tile_sample_min_size=8` - fails to allocate ~6gb with ~20gb already used in SPDA: https://github.com/jy0205/Pyramid-Flow/blob/main/pyramid_dit/modeling_mmdit_block.py#L308

When loading the checkpoints though I get the following warning, so this is probably a ROCm specific issue:
```
using half precision
Using temporal causal attention
We interp the position embedding of condition latents
Using the `SDPA` attention implementation on multi-gpu setup with ROCM may lead to performance issues due to the FA backend. Disabling it to use alternative backends.
```

Thanks for the pointers!

**Comment by feifeiobama** [comment]
> I can confirm that dropping `tile_sample_min_size` to 128 worked for me with `save_memory=True` and `model.vae.enable_tiling()`; peak VRAM was around 22gb @ 384p with a 5s clip taking around 3 mins to generate on a 7900XTX.
> 
> I tried dropping 128->64->32->16->8 to see if 768p would fit, but it OOMs even at `tile_sample_min_size=8` - fails to allocate ~6gb with ~20gb already used in SPDA: https://github.com/jy0205/Pyramid-Flow/blob/main/pyramid_dit/modeling_mmdit_block.py#L308
> 
> When loading the checkpoints though I get the following warning, so this is probably a ROCm specific issue:
> 
> ```
> using half precision
> Using temporal causal attention
> We interp the position embedding of condition latents
> Using the `SDPA` attention implementation on multi-gpu setup with ROCM may lead to performance issues due to the FA backend. Disabling it to use alternative backends.
> ```
> 
> Thanks for the pointers!

Thank you for sharing the findings. If you have multiple GPUs, please stay tuned for our multi-gpu inference that will be released in the next hours.

**Comment by harryaskham** [comment]
The other is an igpu Radeon 780M so not much additional VRAM in my case - disabling this might stop the issue though, will try.

**Comment by marcoseduardopm** [comment]
> The other is an igpu Radeon 780M so not much additional VRAM in my case - disabling this might stop the issue though, will try.

Multi-gpu would be amazing. Thank you for your hard work.

**Comment by marcoseduardopm** [comment]
> Thank you for sharing the findings. If you have multiple GPUs, please stay tuned for our multi-gpu inference that will be released in the next hours.

Just tested the multi-gpu script. It seems like, instead of splitting the model layers between all GPUs, it is trying to load the model(s) at all GPUs at the same time. 

I might be mistaken but, reading the DDP docs at https://pytorch.org/tutorials/intermediate/ddp_tutorial.html ,  they explain that the DDP won't split the model across multiple GPUs: currently, only the 'model parallel' is able to do that currently: 

'Recall from the [prior tutorial](https://pytorch.org/tutorials/intermediate/model_parallel_tutorial.html) that if your model is too large to fit on a single GPU, you must use model parallel to split it across multiple GPUs. DistributedDataParallel works with model parallel; DataParallel does not at this time. When DDP is combined with model parallel, each DDP process would use model parallel, and all processes collectively would use data parallel.'

**Comment by feifeiobama** [comment]
> > Thank you for sharing the findings. If you have multiple GPUs, please stay tuned for our multi-gpu inference that will be released in the next hours.
> 
> Just tested the multi-gpu script. It seems like, instead of splitting the model layers between all GPUs, it is trying to load the model(s) at all GPUs at the same time.
> 
> Reading the DDP docs at https://pytorch.org/tutorials/intermediate/ddp_tutorial.html , they explain that the DDP won't split the model across multiple GPUs: currently, only the 'model parallel' is able to do that currently:
> 
> 'Recall from the [prior tutorial](https://pytorch.org/tutorials/intermediate/model_parallel_tutorial.html) that if your model is too large to fit on a single GPU, you must use model parallel to split it across multiple GPUs. DistributedDataParallel works with model parallel; DataParallel does not at this time. When DDP is combined with model parallel, each DDP process would use model parallel, and all processes collectively would use data parallel.'
> 
> I might be missing something, though.

Thank you for trying our feature. Currently we only support sequence parallelism (SP) instead of pipeline parallelism (PP). This is because we originally implemented it as a precaution in training, and SP is much easier to implement than PP. SP requires loading models on all GPUs, but should reduce memory usage to some extent. We welcome community contributions to support other parallelisms, but may not implement them ourselves in the near future.

**Comment by kalemas** [comment]
Still unable to get 768p even with distributed inference, see screencast below. My setup runs in docker on Linux host with two 4090 and 64Gb RAM.
CPU offloading does not makes an effect. 

Example from provided notebook ends with OOM exception, I am only able to generate with temp=1 or 368p.

https://github.com/user-attachments/assets/42a9465e-a863-400e-ad85-8fa4bbd3a3ef

https://github.com/user-attachments/assets/a4c4b877-533b-492c-ac4b-48d8310ab677

There are monitoring from comfyui captured that display that both GPUs takes a load and there is some ram occupied yet (about a 50%, does it makes sense?).

**Comment by Quasimondo** [comment]
So whilst I was able to generate 384p videos (both t2v and i2v) on my 24GB card with the tile_sample_size=128 fix it only works twice during the same gradio session, the second run already seems to struggle with memory and third attempt gets "killed" with OOM.

So I assume the reason is that there is some data not cleaned from the GPU after a video has been generated. Maybe it's the old latents that stay in memory?

**Comment by Quasimondo** [comment]
So it turned out that in my case the memory issue was not on the GPU but happened in the final step where the frames get retrieved from the GPU and converted to numpy. I have optimized that process and now my crashes went away. Here is my pull request: https://github.com/jy0205/Pyramid-Flow/pull/84

**Comment by feifeiobama** [comment]
> So it turned out that in my case the memory issue was not on the GPU but happened in the final step where the frames get retrieved from the GPU and converted to numpy. I have optimized that process and now my crashes went away. Here is my pull request: #84

The pull request has been merged. Thank you!
